#!/bin/sh
cat > /usr/share/nginx/html/env-config.js << EOF
window.__env__ = {
  "VITE_API_URL": "${VITE_API_URL}",
  "VITE_SOURCE_TOKEN": "${VITE_SOURCE_TOKEN}",
  "VITE_LOCATION_LAT": "${VITE_LOCATION_LAT}",
  "VITE_LOCATION_LON": "${VITE_LOCATION_LON}",
  "VITE_LOCATION_ADDRESS": "${VITE_LOCATION_ADDRESS}",
  "VITE_BOT_USERNAME": "${VITE_BOT_USERNAME}",
  "VITE_TELEGRAM_ADMIN": "${VITE_TELEGRAM_ADMIN}",
  "VITE_TELEGRAM_CHANNEL": "${VITE_TELEGRAM_CHANNEL}",
  "VITE_INSTAGRAM_USERNAME": "${VITE_INSTAGRAM_USERNAME}",
  "VITE_PHONE_NUMBER": "${VITE_PHONE_NUMBER}"
};
EOF
